baseURL = "https://example.com"
languageCode = "en-us"
title = "LeaveIt"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2011
    author = "Covey.Liu"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "我会更好，因为我没有停止"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "xxoo"
    Twitter = "xxoo"
    Email   = "xxoo"
    Instagram = "xxoo"
    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    Facebook = "xxoo"
    Telegram = "xxoo"
    Dribbble = "xxoo"
    Medium = "xxoo"

